### PR TITLE
topic model web tool edits

### PR DESCRIPTION
**Pull request by gordonwoodhull**
Here are Kenny's edits on the Topic Model Web Tool. Additionally, he added one citation and replaced another. LGTM but I thought I'd pass this to @cscheid to approve.

We are one line over, now.

### CODE REVIEW

**Comment by cscheid** [comment]
Only caught one typo: "over the all the unique words"

**Comment by gordonwoodhull** [comment]
fixed

**Comment by gordonwoodhull** [comment]
also a name change

**Comment by gordonwoodhull** [comment]
Merging this.

**Pull request merged**
